# Generated by Django 2.1.5 on 2019-01-14 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='sate',
            new_name='state',
        ),
    ]
