# Generated by Django 2.1.5 on 2019-01-14 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190114_1300'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
