# Generated by Django 2.1.5 on 2019-01-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0003_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image1', models.ImageField(upload_to='')),
                ('quote1', models.CharField(max_length=200, null=True)),
                ('body1', models.TextField()),
                ('image2', models.ImageField(upload_to='')),
                ('quote2', models.CharField(max_length=200, null=True)),
                ('body2', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
